INSERT INTO marca ( Nome) VALUES ( 'Audi'); 
INSERT INTO marca ( Nome) VALUES ( 'Mercedes');
INSERT INTO marca ( Nome) VALUES ( 'BMW');
INSERT INTO marca ( Nome) VALUES ( 'VW');
INSERT INTO marca ( Nome) VALUES ( 'Renault');
INSERT INTO marca ( Nome) VALUES ( 'Volvo'); 
INSERT INTO marca ( Nome) VALUES ( 'Chevrolet'); 
INSERT INTO marca ( Nome) VALUES ( 'Peugeot');
INSERT INTO marca ( Nome) VALUES ( 'Opel');
INSERT INTO marca ( Nome) VALUES ('Fiat');

INSERT INTO taxi (Matricula, Nome, NumeroPassageiros, AnoFabrico, Cor, Gps, IdMarca) VALUES ('12-AA-27', 'Boomer', 4, 2005, 'Vermelho',TRUE, 2);
INSERT INTO taxi (Matricula, Nome, NumeroPassageiros, AnoFabrico, Cor, Gps, IdMarca) VALUES ('MN-22-52', 'Rusty', 4, 1989, 'Azul', FALSE, 7); 
INSERT INTO taxi (Matricula, Nome, NumeroPassageiros, AnoFabrico, Cor, Gps, IdMarca) VALUES ('23-FG-92', 'T-Wrecks', 4, 2010, 'Branco', TRUE, 1); 
INSERT INTO taxi (Matricula, Nome, NumeroPassageiros, AnoFabrico, Cor, Gps, IdMarca) VALUES ('27-AJ-26', 'Jolly Roger', 4, 2006, 'Amarelo', FALSE, 3); 
INSERT INTO taxi (Matricula, Nome, NumeroPassageiros, AnoFabrico, Cor, Gps, IdMarca) VALUES ('PO-32-84', 'T-Bone', 3, 1995, 'Preto', TRUE, 4);
INSERT INTO taxi (Matricula, Nome, NumeroPassageiros, AnoFabrico, Cor, Gps, IdMarca) VALUES  ('19-BH-11', 'Klutch', 6, 2008, 'Verde', TRUE, 6); 
INSERT INTO taxi (Matricula, Nome, NumeroPassageiros, AnoFabrico, Cor, Gps, IdMarca) VALUES ('16-MK-45', 'Mach 1', 4, 2017, 'Bordeaux', TRUE, 5); 
INSERT INTO taxi (Matricula, Nome, NumeroPassageiros, AnoFabrico, Cor, Gps, IdMarca) VALUES ('FF-17-51', 'Chaço', 2, 1990, 'Cinza-Ferrugem', FALSE, 10); 
INSERT INTO taxi (Matricula, Nome, NumeroPassageiros, AnoFabrico, Cor, Gps, IdMarca) VALUES ('76-BN-60', 'Blitz', 4, 2007, 'Branco', TRUE, 8); 
INSERT INTO taxi (Matricula, Nome, NumeroPassageiros, AnoFabrico, Cor, Gps, IdMarca) VALUES ('34-DK-67', 'Siren', 3, 2009, 'Dourado', TRUE, 9);
